// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleTollApi.Infrastructure.Persistence.Data;

#nullable disable

namespace VehicleTollApi.Migrations
{
    [DbContext(typeof(VehicleTollContext))]
    partial class VehicleTollContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("VehicleTollApi.Infrastructure.Persistence.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensePlateNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleKind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VehicleOwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VehicleOwnerId");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("VehicleTollApi.Infrastructure.Persistence.Models.VehicleOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VehicleOwner");
                });

            modelBuilder.Entity("VehicleTollApi.Infrastructure.Persistence.Models.VehiclePassage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensePlateNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PassageDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VehiclePassageInvoiceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VehiclePassageInvoiceId");

                    b.ToTable("VehiclePassage");
                });

            modelBuilder.Entity("VehicleTollApi.Infrastructure.Persistence.Models.VehiclePassageInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("InvoiceDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VehicleOwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VehicleOwnerId");

                    b.ToTable("VehiclePassageInvoice");
                });

            modelBuilder.Entity("VehicleTollApi.Infrastructure.Persistence.Models.Vehicle", b =>
                {
                    b.HasOne("VehicleTollApi.Infrastructure.Persistence.Models.VehicleOwner", "VehicleOwner")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleOwner");
                });

            modelBuilder.Entity("VehicleTollApi.Infrastructure.Persistence.Models.VehiclePassage", b =>
                {
                    b.HasOne("VehicleTollApi.Infrastructure.Persistence.Models.VehiclePassageInvoice", "VehiclePassageInvoice")
                        .WithMany("VehiclePassages")
                        .HasForeignKey("VehiclePassageInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehiclePassageInvoice");
                });

            modelBuilder.Entity("VehicleTollApi.Infrastructure.Persistence.Models.VehiclePassageInvoice", b =>
                {
                    b.HasOne("VehicleTollApi.Infrastructure.Persistence.Models.VehicleOwner", null)
                        .WithMany("VehiclePassageInvoices")
                        .HasForeignKey("VehicleOwnerId");
                });

            modelBuilder.Entity("VehicleTollApi.Infrastructure.Persistence.Models.VehicleOwner", b =>
                {
                    b.Navigation("VehiclePassageInvoices");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleTollApi.Infrastructure.Persistence.Models.VehiclePassageInvoice", b =>
                {
                    b.Navigation("VehiclePassages");
                });
#pragma warning restore 612, 618
        }
    }
}
